# config.yml

backend:
  name:  git-gateway 
  branch: gf-stage # Branch to update (optional; defaults to master)
media_folder: 'gallery/newIma/'
collections:
  - name: "tags"
    label: "Tags"
    folder: 'journal/tag/'
    create: true
    editor:
      preview: false
    widget: "list"
    summary: '{{fields.name}}'
    fields: 
      - {label: Tagname, name: tag_name, widget: string}
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    filter:
    field: language
    value: de
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Subtitle', name: 'subtitel', widget: 'string' }
      - { 
        label: 'Header-Image',
        name: 'header', 
        widget: 'relation',
        collection: 'picturs'
        }
      - {
          label: 'Author',
          name: 'author',
          widget: 'relation',
          collection: 'authors',
          display_fields: [display_name],
          search_fields: [display_name],
          value_field: 'name',
        }
      - {label: "Language", name: "language"}
      - {
        label: "Tags",
        name: "tags",
        widget: 'relation',
        collection: 'authors',
        display_fields: [tag_name],
        search_fields: [tag_name],
        value_field: 'tag_name',
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'authors'
    label: 'Authors'
    folder: '_authors/'
    create: true
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'author' }
      - { label: 'Short Name', name: 'name', widget: 'string' }
      - { label: 'Display Name', name: 'display_name', widget: 'string' }
      - { label: 'Position', name: 'position', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'pages'
    label: 'Pages'
    editor:
      preview: false
    files:
    - label: 'About Page'
      name: 'about'
      file: 'about.md'
      fields:
        - { label: 'Title', name: 'title', widget: 'hidden', default: 'about' }
        - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'about' }
        - { label: 'Body', name: 'body', widget: 'markdown' }

